version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lamda-nk1-amount"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-19aakvd7i0ucw"
s3_prefix = "lamda-nk1-amount"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
